security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    role_hierarchy:
        ROLE_MEMBER:      [ROLE_USER]
        ROLE_MODERATOR:   [ROLE_MODERATOR]
        ROLE_ADMIN:       [ROLE_ADMIN]

    providers:
        entity_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        swagger_ui:
            pattern:  ^/api/doc
            security: false
        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            json_login:
                check_path: /login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        register:
            pattern:  ^/register
            stateless: true
            anonymous: true

        api:
            pattern:  ^/api
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        addCategory:
            pattern:  ^/addCategory
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        editCategory:
            pattern:  ^/editCategory
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        deleteCategory:
            pattern:  ^/deleteCategory
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        categories:
            pattern:  ^/categories
            stateless: true
            anonymous: true
        category:
            pattern:  ^/category
            stateless: true
            anonymous: true
        addTopic:
            pattern:  ^/addTopic
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        editTopic:
            pattern:  ^/editTopic
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        deleteTopic:
            pattern:  ^/deleteTopic
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        topics:
            pattern:  ^/topics
            stateless: true
            anonymous: true
        topic:
            pattern:  ^/topic
            stateless: true
            anonymous: true
        addReply:
            pattern:  ^/addReply
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        editReply:
            pattern:  ^/editReply
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        deleteReply:
            pattern:  ^/deleteReply
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        replies:
            pattern:  ^/replies
            stateless: true
            anonymous: true
        reply:
            pattern:  ^/reply
            stateless: true
            anonymous: true
        promoteUser:
            pattern:  ^/promoteUser
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        countReplies:
            pattern:  ^/countReplies
            stateless: true
            anonymous: true
        countTopics:
            pattern:  ^/countTopics
            stateless: true
            anonymous: true
        addComment:
            pattern:  ^/addComment
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        editComment:
            pattern:  ^/editComment
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        deleteComment:
            pattern:  ^/deleteComment
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        comments:
            pattern:  ^/comments
            stateless: true
            anonymous: true
        comment:
            pattern:  ^/comment
            stateless: true
            anonymous: true
        addVote:
            pattern:  ^/addVote
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        countVotes:
            pattern:  ^/countVotes
            stateless: true
            anonymous: true
        setCorrectAnswer:
            pattern:  ^/setCorrectAnswer
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        setUserStatus:
            pattern:  ^/setUserStatus
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        setResolved:
            pattern:  ^/setResolved
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        setUnresolved:
            pattern:  ^/setUnresolved
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        setTopicClose:
            pattern:  ^/setTopicClose
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        setTopicOpen:
            pattern:  ^/setTopicOpen
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        totalPosts:
            pattern:  ^/totalPosts
            stateless: true
            anonymous: true
        allTotalPosts:
            pattern:  ^/allTotalPosts
            stateless: true
            anonymous: true
        passwordChange:
            pattern:  ^/passwordChange
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        setProfilePicture:
            pattern:  ^/setProfilePicture
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        editProfile:
            pattern:  ^/editProfile
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        profileShow:
            pattern:  ^/profileShow
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        removeProfilePicture:
            pattern:  ^/removeProfilePicture
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        userShow:
            pattern:  ^/userShow
            stateless: true
            anonymous: true
        swagger:
            pattern:  ^/api/doc.json
            stateless: true
            anonymous: true
        repliesByTopic:
            pattern:  ^/repliesByTopic
            stateless: true
            anonymous: true
        commentsByReply:
            pattern:  ^/commentsByReply
            stateless: true
            anonymous: true
        topicsByCategory:
            pattern:  ^/topicsByCategory
            stateless: true
            anonymous: true
        deactivateUser:
            pattern:  ^/deactivateUser
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        activateUser:
            pattern:  ^/activateUser
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        users:
            pattern:  ^/users
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/addCategory, roles: [ROLE_ADMIN, ROLE_MODERATOR] }
        - { path: ^/editCategory, roles: [ROLE_ADMIN, ROLE_MODERATOR] }
        - { path: ^/deleteCategory, roles: [ROLE_ADMIN, ROLE_MODERATOR] }
        - { path: ^/categories, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/category, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/addTopic, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/editTopic, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/deleteTopic, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/topics, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/topic, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/addReply, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/editReply, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/deleteReply, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/replies, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/reply, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/promoteUser, roles: ROLE_ADMIN }
        - { path: ^/countReplies, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/countTopics, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/addComment, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/editComment, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/deleteComment, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/comments, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/comment, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/addVote, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/countVotes, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/setCorrectAnswer, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/setUserStatus, roles: ROLE_MODERATOR }
        - { path: ^/setResolved, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/setUnresolved, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/setTopicClose, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/setTopicOpen, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/totalPosts, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/allTotalPosts, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/passwordChange, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/setProfilePicture, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/editProfile, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/profileShow, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/userShow, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/removeProfilePicture, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/doc.json, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/doc, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/repliesByTopic, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/commentsByReply, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/topicsByCategory, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/activateUser, roles: ROLE_ADMIN }
        - { path: ^/deactivateUser, roles: ROLE_ADMIN }
        - { path: ^/users, roles: [ROLE_ADMIN, ROLE_MODERATOR] }
