security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        entity_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            json_login:
                check_path: /login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        register:
            pattern:  ^/register
            stateless: true
            anonymous: true

        api:
            pattern:  ^/api
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        addCategory:
            pattern:  ^/addCategory
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        editCategory:
            pattern:  ^/editCategory
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        deleteCategory:
            pattern:  ^/deleteCategory
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        categories:
            pattern:  ^/categories
            stateless: true
            anonymous: true
        category:
            pattern:  ^/category
            stateless: true
            anonymous: true
        addTopic:
            pattern:  ^/addTopic
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        editTopic:
            pattern:  ^/editTopic
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        deleteTopic:
            pattern:  ^/deleteTopic
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        topics:
            pattern:  ^/topics
            stateless: true
            anonymous: true
        topic:
            pattern:  ^/topic
            stateless: true
            anonymous: true
        addReply:
            pattern:  ^/addReply
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        editReply:
            pattern:  ^/editReply
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        deleteReply:
            pattern:  ^/deleteReply
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        replies:
            pattern:  ^/replies
            stateless: true
            anonymous: true
        reply:
            pattern:  ^/reply
            stateless: true
            anonymous: true
        promoteUser:
            pattern:  ^/promoteUser
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/addCategory, roles: ROLE_ADMIN }
        - { path: ^/editCategory, roles: ROLE_ADMIN }
        - { path: ^/deleteCategory, roles: ROLE_ADMIN }
        - { path: ^/categories, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/category, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/addTopic, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/editTopic, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/deleteTopic, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/topics, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/topic, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/addReply, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/editReply, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/deleteReply, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/replies, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/reply, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/promoteUser, roles: ROLE_ADMIN }
