register:
    path: /register
    controller: App\Controller\DefaultController::register
    methods: [POST]
    defaults:
        _format: json

api:
    path: /api
    controller: App\Controller\DefaultController::api
    defaults:
        _format: json

login_check:
    path:     /login_check
    methods:  [POST]
    defaults:
        _format: json

addCategory:
    path:     /addCategory
    controller: App\Controller\CategoriesController::addCategory
    methods:  [POST]
    defaults:
        _format: json
editCategory:
    path:     /editCategory/{id}
    controller: App\Controller\CategoriesController::editCategory
    methods:  [PUT]
    defaults:
        _format: json
deleteCategory:
    path:     /deleteCategory/{id}
    controller: App\Controller\CategoriesController::deleteCategory
    methods:  [POST]
    defaults:
        _format: json
categories:
    path:     /categories
    controller: App\Controller\CategoriesController::categories
    methods:  [GET]
    defaults:
        _format: json
category:
    path:     /category/{id}
    controller: App\Controller\CategoriesController::category
    methods:  [GET]
    defaults:
        _format: json
addTopic:
    path:     /addTopic
    controller: App\Controller\TopicsController::addTopic
    methods:  [POST]
    defaults:
        _format: json
editTopic:
    path:     /editTopic/{id}
    controller: App\Controller\TopicsController::editTopic
    methods:  [PUT]
    defaults:
        _format: json
deleteTopic:
    path:     /deleteTopic/{id}
    controller: App\Controller\TopicsController::deleteTopic
    methods:  [POST]
    defaults:
        _format: json
topics:
    path:     /topics
    controller: App\Controller\TopicsController::topics
    methods:  [GET]
    defaults:
        _format: json
topic:
    path:     /topic/{id}
    controller: App\Controller\TopicsController::topic
    methods:  [GET]
    defaults:
        _format: json
addReply:
    path:     /addReply
    controller: App\Controller\RepliesController::addReply
    methods:  [POST]
    defaults:
        _format: json
editReply:
    path:     /editReply/{id}
    controller: App\Controller\RepliesController::editReply
    methods:  [PUT]
    defaults:
        _format: json
deleteReply:
    path:     /deleteReply/{id}
    controller: App\Controller\RepliesController::deleteReply
    methods:  [POST]
    defaults:
        _format: json
replies:
    path:     /replies
    controller: App\Controller\RepliesController::replies
    methods:  [GET]
    defaults:
        _format: json
reply:
    path:     /reply/{id}
    controller: App\Controller\RepliesController::reply
    methods:  [GET]
    defaults:
        _format: json
promoteUser:
    path:     /promoteUser/{id}
    controller: App\Controller\DefaultController::promoteUser
    methods:  [PUT]
    defaults:
        _format: json
countReplies:
    path:     /countReplies/{id}
    controller: App\Controller\TopicsController::countReplies
    methods:  [GET]
    defaults:
        _format: json
countTopics:
    path:     /countTopics/{id}
    controller: App\Controller\CategoriesController::countTopics
    methods:  [GET]
    defaults:
        _format: json
addComment:
    path:     /addComment
    controller: App\Controller\CommentsController::addComment
    methods:  [POST]
    defaults:
        _format: json
editComment:
    path:     /editComment/{id}
    controller: App\Controller\CommentsController::editComment
    methods:  [PUT]
    defaults:
        _format: json
deleteComment:
    path:     /deleteComment/{id}
    controller: App\Controller\CommentsController::deleteComment
    methods:  [POST]
    defaults:
        _format: json
comments:
    path:     /comments
    controller: App\Controller\CommentsController::comments
    methods:  [GET]
    defaults:
        _format: json
comment:
    path:     /comment/{id}
    controller: App\Controller\CommentsController::comment
    methods:  [GET]
    defaults:
        _format: json
addVote:
    path:     /addVote
    controller: App\Controller\VotesController::addVote
    methods:  [POST]
    defaults:
        _format: json
countVotes:
    path:     /countVotes/{id}
    controller: App\Controller\RepliesController::countVotes
    methods:  [GET]
    defaults:
        _format: json
setCorrectAnswer:
    path:     /setCorrectAnswer/{id}
    controller: App\Controller\RepliesController::setCorrectAnswer
    methods:  [PUT]
    defaults:
        _format: json
setUserStatus:
    path:     /setUserStatus/{id}
    controller: App\Controller\ModeratorController::setUserStatus
    methods:  [PUT]
    defaults:
        _format: json
setResolved:
    path:     /setResolved/{id}
    controller: App\Controller\TopicsController::setResolved
    methods:  [PUT]
    defaults:
        _format: json
setUnresolved:
    path:     /setUnresolved/{id}
    controller: App\Controller\TopicsController::setUnresolved
    methods:  [PUT]
    defaults:
        _format: json
setTopicClose:
    path:     /setTopicClose/{id}
    controller: App\Controller\TopicsController::setTopicClose
    methods:  [PUT]
    defaults:
        _format: json
setTopicOpen:
    path:     /setTopicOpen/{id}
    controller: App\Controller\TopicsController::setTopicOpen
    methods:  [PUT]
    defaults:
        _format: json
totalPosts:
    path:     /totalPosts/{id}
    controller: App\Controller\UserController::totalPosts
    methods:  [GET]
    defaults:
        _format: json
allTotalPosts:
    path:     /allTotalPosts
    controller: App\Controller\DefaultController::allTotalPosts
    methods:  [GET]
    defaults:
        _format: json
passwordChange:
    path:     /passwordChange/{id}
    controller: App\Controller\UserController::passwordChange
    methods:  [PUT]
    defaults:
        _format: json
setProfilePicture:
    path:     /setProfilePicture/{id}
    controller: App\Controller\UserController::setProfilePicture
    methods:  [POST]
    defaults:
        _format: json
editProfile:
    path:     /editProfile/{id}
    controller: App\Controller\UserController::editProfile
    methods:  [PUT]
    defaults:
        _format: json
userShow:
    path:     /userShow/{id}
    controller: App\Controller\UserController::userShow
    methods:  [GET]
    defaults:
        _format: json
profileShow:
    path:     /profileShow/{id}
    controller: App\Controller\UserController::profileShow
    methods:  [GET]
    defaults:
        _format: json
removeProfilePicture:
    path:     /removeProfilePicture/{id}
    controller: App\Controller\UserController::removeProfilePicture
    methods:  [POST]
    defaults:
        _format: json
swagger:
    path: /api/doc.json
    methods: [GET]
    defaults: { _controller: nelmio_api_doc.controller.swagger }
swagger_ui:
    path: /api/doc
    methods: [GET]
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
repliesByTopic:
    path: /repliesByTopic/{id}
    controller: App\Controller\TopicsController::repliesByTopic
    methods: [GET]
    defaults:
        _format: json
commentsByReply:
    path: /commentsByReply/{id}
    controller: App\Controller\RepliesController::commentsByReply
    methods: [GET]
    defaults:
        _format: json
topicsByCategory:
    path: /topicsByCategory/{id}
    controller: App\Controller\CategoriesController::topicsByCategory
    methods: [GET]
    defaults:
        _format: json