register:
    path: /register
    controller: App\Controller\DefaultController::register
    methods: [POST]
    defaults:
        _format: json

api:
    path: /api
    controller: App\Controller\DefaultController::api
    defaults:
        _format: json

login_check:
    path:     /login_check
    methods:  [POST]
    defaults:
        _format: json

addCategory:
    path:     /addCategory
    controller: App\Controller\CategoriesController::addCategory
    methods:  [POST]
    defaults:
        _format: json
editCategory:
    path:     /editCategory/{id}
    controller: App\Controller\CategoriesController::editCategory
    methods:  [PUT]
    defaults:
        _format: json
deleteCategory:
    path:     /deleteCategory/{id}
    controller: App\Controller\CategoriesController::deleteCategory
    methods:  [POST]
    defaults:
        _format: json
categories:
    path:     /categories
    controller: App\Controller\CategoriesController::categories
    methods:  [GET]
    defaults:
        _format: json
category:
    path:     /category/{id}
    controller: App\Controller\CategoriesController::category
    methods:  [GET]
    defaults:
        _format: json
addTopic:
    path:     /addTopic
    controller: App\Controller\TopicsController::addTopic
    methods:  [POST]
    defaults:
        _format: json
editTopic:
    path:     /editTopic/{id}
    controller: App\Controller\TopicsController::editTopic
    methods:  [PUT]
    defaults:
        _format: json
deleteTopic:
    path:     /deleteTopic/{id}
    controller: App\Controller\TopicsController::deleteTopic
    methods:  [POST]
    defaults:
        _format: json
topics:
    path:     /topics
    controller: App\Controller\TopicsController::topics
    methods:  [GET]
    defaults:
        _format: json
topic:
    path:     /topic/{id}
    controller: App\Controller\TopicsController::topic
    methods:  [GET]
    defaults:
        _format: json